name: Test Template Generators

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'module-generation-cli'

jobs:
  generate_and_run_module:
    # if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        resource: [
          "arm component", 
          "audio_input component",
          "base component",
          "board component",
          "camera component",
          "encoder component",
          "gantry component",
          "generic component",
          "gripper component",
          "input component",
          "motor component",
          "movement_sensor component",
          "pose_tracker component",
          "power_sensor component",
          "sensor component",
          "servo component",
      
          "generic service",
          "mlmodel service",
          "motion service",
          "navigation service",
          "sensors service",
          "slam service",
          "vision service"
          ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run module generator
        run: |
          cd cli/viam
          go run . module generate --resource "${{ matrix.resource }}"

      - name: Run module
        run: |
          cd cli/viam/my-module
          chmod +x run.sh
          ./run.sh /tmp/viam.sock &
          PID=$!
          sleep 5
          if ps -p $PID > /dev/null; then
              echo "Module is running."
              kill -SIGTERM $PID
          else
              echo "Module failed to start."
              exit 1
          fi
